### ISSUE TITLE
Docker networking issue when routing through API gateway for authenticated routes.

### ISSUE THREAD

**Issue by chinthaka-dinadasa** [JavatoDev-com/internet-banking-concept-microservices#51]
When application running with docker compose if we use keycloak jwk uri as below.

```jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs```

```
## SECURITY BASED CONFIGURATIONS
app:
  config:
    keycloak:
      url: http://keyloak_web:8080
      realm: javatodev-internet-banking
```

This creates and error when we are accessing authenticated API paths, since the API gateway authentication layer coudn't capture keycloak instance with path definition above.
